In [164]:
import numpy as np
import pandas as pd

In [165]:
df=pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [166]:
df=df.astype('float128')

In [167]:
target_output=np.array(df["Outcome"])
target_output

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [168]:
target_output.shape
target_output=target_output.reshape(768,1)
target_output.shape

(768, 1)

In [169]:
type(target_output)

numpy.ndarray

In [170]:
df=df.drop(columns=["Outcome"])

In [171]:
df.dtypes

Pregnancies                 float128
Glucose                     float128
BloodPressure               float128
SkinThickness               float128
Insulin                     float128
BMI                         float128
DiabetesPedigreeFunction    float128
Age                         float128
dtype: object

In [172]:
input_features=[]
for i in range(len(df)):
  input_features.append(df.loc[i])
input_features=np.array(input_features)

In [173]:
input_features.shape
input_features.dtype

dtype('float128')

In [174]:
w_ji = np.random.uniform(low=-0.02, high=0, size=(8,6))
w_ji.astype('float128')

array([[-0.00588415, -0.01806475, -0.00498748, -0.01116776, -0.00913831,
        -0.01162147],
       [-0.01881272, -0.0082145 , -0.00615593, -0.00366801, -0.00580634,
        -0.01440349],
       [-0.01435086, -0.01194976, -0.01109204, -0.00725561, -0.00841264,
        -0.00014579],
       [-0.01837711, -0.01362842, -0.0175738 , -0.01024085, -0.00937033,
        -0.00991347],
       [-0.00821706, -0.0163911 , -0.00624318, -0.01800529, -0.0128537 ,
        -0.00419317],
       [-0.00702664, -0.01789494, -0.00704384, -0.01858461, -0.01290952,
        -0.01019661],
       [-0.00651898, -0.0082813 , -0.0006898 , -0.01589195, -0.0197973 ,
        -0.01085862],
       [-0.00608572, -0.01522803, -0.00549952, -0.0004015 , -0.00998538,
        -0.01483696]], dtype=float128)

In [175]:
w_ji.shape

(8, 6)

In [176]:
w_kj = np.random.uniform(low=-0.02, high=0, size=(6,1))
w_kj.astype('float128')

array([[-0.01124303],
       [-0.00562865],
       [-0.01780486],
       [-0.00482727],
       [-0.01706554],
       [-0.01710559]], dtype=float128)

In [177]:
w_kj.shape

(6, 1)

In [178]:
lr=0.001
def sigmoid (x):
    return 1/(1+np.exp(-x))

In [179]:
for epoch in range(150000):
    net_j=np.dot(input_features,w_ji)
    oj= sigmoid(net_j)
    net_k=np.dot(oj,w_kj)
    ok=sigmoid(net_k)

    error_out=((1/2)* (np.power((ok-target_output),2)))
    print(error_out.sum())

    #phase 1
    delt_k=(ok*(1-ok))*(ok - target_output)
    z1=np.dot(oj.T, delt_k)

    #phase 2
    s=np.dot(delt_k, w_kj.T)
    delt_j=(oj*(1-oj))*s
    z2=np.dot(input_features.T,delt_j)

    w_kj=w_kj-lr*z1
    w_ji=w_ji-lr*z2

Görüntülenen çıkış son 5000 satıra kısaltıldı.
63.348731093851904372
63.4522396209766602
63.18407406396573608
63.318917515211786132
63.438909823120119738
63.35457320656829417
63.453412629924568093
63.486426519959389174
63.186687230662416714
63.310083133201075174
63.45902238169470516
63.33938670221763617
63.481028042885867813
63.443910203315334508
63.303250444105256756
63.068259812332413912
63.239671622204645704
63.23168650630633849
63.53701843590518615
63.545620455161337482
63.238622113739670377
63.097260187028701192
63.34088707308359157
63.104796640942590395
63.314880686930214225
63.079733668405664544
63.233660832668264026
63.32757741858227278
63.519189213900196338
63.376610277148096008
63.584570058829688224
63.441694132715085553
63.893698869500100745
63.64914797763322078
63.471281778121212396
63.15019215254144004
63.398523711981891904
63.133235272103525208
63.312292730532421396
63.073523940575771142
63.15804353813643674
63.036098776351901573
63.18298136308040351
63.162333803926675707

In [180]:
p=np.array([1	,126,	60	,0,	180	,30.1	,0.349,	47	],dtype=np.float128)
r1=np.dot(p,w_ji)
r2=sigmoid(r1)
r3=np.dot(r2,w_kj)
r4=sigmoid(r3)
print(r4)

[0.71158715]
